const PINK = '#fa65c5';
const WHITE = "#76d9e6";
const BLUE = '#ffffff';
const PURPLE = '#a77afe';

export default {
  'code[class*="language-"]': {
    MozTabSize: '4',
    OTabSize: '4',
    tabSize: '4',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    whiteSpace: 'pre-wrap',
    wordWrap: 'normal',
    fontFamily: 'Menlo, Monaco, "Courier New", monospace',
    fontSize: '14px',
    lineHeight: '20px',
    color: WHITE,
    textShadow: 'none'
  },
  'pre[class*="language-"]': {
    MozTabSize: '2',
    OTabSize: '2',
    tabSize: '2',
    WebkitHyphens: 'none',
    MozHyphens: 'none',
    msHyphens: 'none',
    hyphens: 'none',
    whiteSpace: 'pre-wrap',
    wordWrap: 'normal',
    fontFamily: 'Menlo, Monaco, "Courier New", monospace',
    fontSize: '14px',
    color: WHITE,
    textShadow: 'none',
    background: '#211f42',
    padding: '15px',
    borderRadius: '7px',
    overflow: 'auto',
    position: 'relative'
  },
  ':not(pre)>code[class*="language-"]': {
    background: '#2a2a2a',
    padding: '0.15em 0.2em 0.05em',
    borderRadius: '.3em',
    border: '0.13em solid #7a6652',
    boxShadow: '1px 1px 0.3em -0.1em #000 inset'
  },
  'pre[class*="language-"] code': { whiteSpace: 'pre', display: 'block' },
  namespace: { Opacity: '.7' },
  comment: { color: '#6f705e' },
  prolog: { color: '#6f705e' },
  doctype: { color: '#6f705e' },
  cdata: { color: '#6f705e' },
  operator: { color: PURPLE },
  boolean: { color: PURPLE },
  number: { color: PURPLE },
  'attr-name': { color: BLUE },
  string: { color: BLUE },
  entity: { color: BLUE, cursor: 'help' },
  url: { color: BLUE },
  '.language-css .token.string': { color: BLUE },
  '.style .token.string': { color: BLUE },
  selector: { color: '#a6e22d' },
  inserted: { color: '#a6e22d' },
  atrule: { color: PINK },
  'attr-value': { color: PINK },
  keyword: { color: PINK },
  important: { color: PINK, fontWeight: 'bold' },
  deleted: { color: PINK },
  regex: { color: WHITE },
  statement: { color: WHITE, fontWeight: 'bold' },
  placeholder: { color: '#fff' },
  variable: { color: '#fff' },
  bold: { fontWeight: 'bold' },
  punctuation: { color: '#bebec5' },
  italic: { fontStyle: 'italic' },
  'code.language-markup': { color: '#f9f9f9' },
  'code.language-markup .token.tag': { color: PINK },
  'code.language-markup .token.attr-name': { color: '#a6e22d' },
  'code.language-markup .token.attr-value': { color: BLUE },
  'code.language-markup .token.style': { color: WHITE },
  'code.language-markup .token.script': { color: WHITE },
  'code.language-markup .token.script .token.keyword': { color: WHITE },
  'pre[class*="language-"][data-line]': { position: 'relative', padding: '1em 0 1em 3em' },
  'pre[data-line] .line-highlight': {
    position: 'absolute',
    left: '0',
    right: '0',
    padding: '0',
    marginTop: '1em',
    background: 'rgba(255, 255, 255, 0.08)',
    pointerEvents: 'none',
    lineHeight: 'inherit',
    whiteSpace: 'pre'
  },
  'pre[data-line] .line-highlight:before': {
    content: 'attr(data-start)',
    position: 'absolute',
    top: '.4em',
    left: '.6em',
    minWidth: '1em',
    padding: '0.2em 0.5em',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    color: 'black',
    font: 'bold 65%/1 sans-serif',
    height: '1em',
    lineHeight: '1em',
    textAlign: 'center',
    borderRadius: '999px',
    textShadow: 'none',
    boxShadow: '0 1px 1px rgba(255, 255, 255, 0.7)'
  },
  'pre[data-line] .line-highlight[data-end]:after': {
    content: 'attr(data-end)',
    position: 'absolute',
    top: 'auto',
    left: '.6em',
    minWidth: '1em',
    padding: '0.2em 0.5em',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    color: 'black',
    font: 'bold 65%/1 sans-serif',
    height: '1em',
    lineHeight: '1em',
    textAlign: 'center',
    borderRadius: '999px',
    textShadow: 'none',
    boxShadow: '0 1px 1px rgba(255, 255, 255, 0.7)',
    bottom: '.4em'
  }
}